# List of source URLs to fetch proxy configurations from.
SOURCE_URLS = [
    "https://dev1.irdevs.sbs",
    "https://raw.githubusercontent.com/DarknessShade/Sub/main/V2mix",
    "https://raw.githubusercontent.com/DiDiten/HiN-VPN/main/subscription/normal/mix",
    "https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt",
    "https://raw.githubusercontent.com/Epodonios/v2ray-configs/refs/heads/main/Sub1.txt",
    "https://raw.githubusercontent.com/Epodonios/v2ray-configs/refs/heads/main/Sub2.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista4.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista5.txt",
    "https://raw.githubusercontent.com/Rayan-Config/C-Sub/refs/heads/main/configs/proxy.txt",
    "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/Protocols/ss.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/V2RAY_RAW.txt",
    "https://raw.githubusercontent.com/MahsaNetConfigTopic/config/refs/heads/main/xray_final.txt",
    "https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/refs/heads/main/mix/sub.html",
    "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/refs/heads/master/Eternity.txt",
    "https://raw.githubusercontent.com/itsyebekhe/PSG/refs/heads/main/subscriptions/xray/normal/mix",
    "https://raw.githubusercontent.com/kayhgng/v2raykayh/refs/heads/main/kayhgngcollectorv3v2ray_ss",
    "https://raw.githubusercontent.com/10ium/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt",

    "https://t.me/s/v2ray_Extractor",
    "https://t.me/s/BINNER_IRAN",
    "https://t.me/s/DeamNet",
    "https://t.me/s/AzadNet",
    "https://t.me/s/freeconfigsplus",
    "https://t.me/s/ConfigWireguard",
    "https://t.me/s/WireVpnGuard",
    "https://t.me/s/Config_Vortex55",
    "https://t.me/s/configshubplus",
    "https://t.me/s/APPXA",
    "https://t.me/s/arshia_mod_fun",
    "https://t.me/s/lightning6",
    "https://t.me/s/spotify_porteghali",
    "https://t.me/s/kvetch_matin",
    "https://t.me/s/hacknashid",
    "https://t.me/s/lnrbymaa",
    "https://t.me/s/lyricpixelart",
    "https://t.me/s/madshopx",
    "https://t.me/s/movie10_oficial",
    "https://t.me/s/mbtiuniverse",
    "https://t.me/s/mitivpn",
    "https://t.me/s/soskeynet",
    "https://t.me/s/surfboardv2ray",
    "https://t.me/s/v2ray1_ng",
    "https://t.me/s/v2ray_vpn_ir",
    "https://t.me/s/vlessconfight",
    "https://t.me/s/vpn4everyone",
    "https://t.me/s/vpnbaz",
    "https://t.me/s/vpnserverrr",
    "https://t.me/s/xixv2ray",
    "https://t.me/s/ahwazigamingshop",
    "https://t.me/s/ar14n24b",
    "https://t.me/s/betv2ray",
    "https://t.me/s/bugfreenet",
    "https://t.me/s/capoit",
    "https://t.me/s/canfing_vpn",
    "https://t.me/s/configfa",
    "https://t.me/s/configx2ray",
    "https://t.me/s/crypto_trad26",
    "https://t.me/s/express_freevpn",
    "https://t.me/s/gp_config",
    "https://t.me/s/lrnbymaa",
    "https://t.me/s/mrsoulb",
    "https://t.me/s/proxy_confiig",
    "https://t.me/s/proxyiranip",
    "https://t.me/s/club_profsor",
    "https://t.me/s/shadowproxy66",
    "https://t.me/s/speeds_vpn1",
    "https://t.me/s/vless_config",
    "https://t.me/s/vpn_solve",
    "https://t.me/s/shadowsocksm",
    "https://t.me/s/v2ray_alpha",
    "https://t.me/s/vlessconfig",
    "https://t.me/s/v2rayngvpn",
    "https://t.me/s/an0nymousteam",
    "https://t.me/s/oneclickvpnkeys",
    "https://t.me/s/cav2ray",
    "https://t.me/s/eliv2ray",
    "https://t.me/s/mehradlearn",
    "https://t.me/s/outline_vpn",
    "https://t.me/s/safenet_server",
    "https://t.me/s/vpn_king_v2ray",
    "https://t.me/s/ipv2ray",
    "https://t.me/s/proxy_kafee",
    "https://t.me/s/proxy_mtm",
    "https://t.me/s/v2rayng_vpnn",
    "https://t.me/s/tv2rayrr",
    "https://t.me/s/v2rey_hiddify",
    "https://t.me/s/server_nekobox",
    "https://t.me/s/v2rayngn",
    "https://t.me/s/v2raying",
    "https://t.me/s/s0013_official",
    "https://t.me/s/v2rayroz",
    "https://t.me/s/v2rayng_outlinee",
    "https://t.me/s/sinavm",
    "https://t.me/s/customv2ray",
    "https://t.me/s/fastkanfig",
    "https://t.me/s/vpnstorefast",
    "https://t.me/s/hope_net",
    "https://t.me/s/oxnet_ir",
    "https://t.me/s/cryptoguardvpn",
    "https://t.me/s/freeiranianv2rey",
    "https://t.me/s/ernoxin_shop",
    "https://t.me/s/darkvpnpro",
    "https://t.me/s/free_vpn_for_all_of_us",
    "https://t.me/s/noforcedheaven",
    "https://t.me/s/v2raybaz",
    "https://t.me/s/freedomofinfor",
    "https://t.me/s/vpnstable",
    "https://t.me/s/orange_vpns",
    "https://t.me/s/amirtronic",
    "https://t.me/s/kb_v2ray_store",
    "https://t.me/s/v2ray_free_conf",
    "https://t.me/s/PrivateVPNs",
    "https://t.me/s/prrofile_purple",
    "https://t.me/s/DirectVPN",
    "https://t.me/s/freevpnhomesconfigs",
    "https://t.me/s/ahmedhamoomi_servers",
    "https://t.me/s/v2ray_nima02",
    "https://t.me/s/isvvpn",
    "https://t.me/s/prossh",
    "https://t.me/s/v2ray_hub1",
    "https://t.me/s/grizzlyvpn",
    "https://t.me/s/bestforbest66",
    "https://t.me/s/curetech",
    "https://t.me/s/v2source",
    "https://t.me/s/getconfigir",
    "https://t.me/s/parsashonam",
    "https://t.me/s/arv2ray",
    "https://t.me/s/change_ip1",
    "https://t.me/s/vpncustomize",
    "https://t.me/s/suevpnx",
    "https://t.me/s/nfastvpnn",
    "https://t.me/s/napsternetv",
    "https://t.me/s/alpha_v2ray_iran",
    "https://t.me/s/vpn_proxy666",
    "https://t.me/s/xsfilternet",
    "https://t.me/s/hiidify_v2ray",
    "https://t.me/s/lonup_m",
    "https://t.me/s/configv2rayng",
    "https://t.me/s/v2ray_tunnel_plus",
    "https://t.me/s/cookvip",
    "https://t.me/s/v2rayfree",
    "https://t.me/s/freev2rays",
    "https://t.me/s/ip_cf_config",
    "https://t.me/s/outlinereleasedkey",
    "https://t.me/s/proxy_shadosocks",
    "https://t.me/s/meli_proxyy",
    "https://t.me/s/vmessprotocol",
    "https://t.me/s/viproxys",
    "https://t.me/s/heyatserver",
    "https://t.me/s/vpnfail_vless",
    "https://t.me/s/dailyv2ry",
    "https://t.me/s/qv2rayconfig",
    "https://t.me/s/xsfilternetv2",
    "https://t.me/s/redfree8",
    "https://t.me/s/v2sayfree",
    "https://t.me/s/safenet4all",
    "https://t.me/s/golestan_vpn",
    "https://t.me/s/mehduox_vpn",
    "https://t.me/s/kayh_gng",
    "https://t.me/s/xrovpn",
    "https://t.me/s/viturey",
    "https://t.me/s/freedom_guard_net",
    "https://t.me/s/ln2ray",
    "https://t.me/s/zeusvpn_net",
    "https://t.me/s/v2nodes",
    "https://t.me/s/v2box_free",
    "https://t.me/s/vpnaloo",
    "https://t.me/s/v2ray_hidify",
    "https://t.me/s/purnet",
    "https://t.me/s/begzarvpn",
    "https://t.me/s/proxydaemi",
    "https://t.me/s/slamvpn",
    "https://t.me/s/vpnz4",
    "https://t.me/s/hack_androidapp1",
    "https://t.me/s/p_tech2024",
    "https://t.me/s/yebekhe",
    "https://t.me/s/fr33c0nfig",
    "https://t.me/s/aristaproject",
    "https://t.me/s/kevinzakarian",
    "https://t.me/s/marambashi",
    "https://t.me/s/prooofsor",
    "https://t.me/s/asrnovin_ir",
    "https://t.me/s/conectvpn10",
    "https://t.me/s/beau_vpn"
]

# Set to True to fetch the maximum possible number of configurations.
# If True, SPECIFIC_CONFIG_COUNT will be ignored.
USE_MAXIMUM_POWER = False
# Desired number of configurations to fetch.
# This is used only if USE_MAXIMUM_POWER is False.
SPECIFIC_CONFIG_COUNT = 1000
# Maximum age of configurations in days.
# Configurations older than this will be considered invalid.
MAX_CONFIG_AGE_DAYS = 4
# Dictionary of protocols to enable or disable.
# Set each protocol to True to enable, False to disable.
ENABLED_PROTOCOLS = {
    "wireguard://": True,
    "hysteria2://": True,
    "vless://": True,
    "vmess://": True,
    "ss://": True,
    "trojan://": True,
    "tuic://": False,
}
